#-------------------------------
# Site Settings
title: Amit Mondal
description: Personal Blog
logo: # You can add own logo. For example '/images/logo.png'.
logo_dark:


#-------------------------------
# Color Scheme Settings
color_scheme:
  default: dark # Default theme applied on the first visit (options: "light" or "dark")
  toggle: true # Enable theme toggle

# Enables or disables the theme toggle functionality:
# - true: Users can switch between light and dark modes using a toggle button.
#          The site will remember their choice for future visits.
# - false: The theme will always use the default mode specified above,
#          and the toggle button will not be displayed.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: 'Home'
      url: '/'
    #- title: 'Videos'
    #- url: '/videos/'
    - title: 'Archive'
      url: '/archive/'
    #- title: 'About'
    #  url: '/about/'
    # - title: 'Pages'
     # submenu:
      #- url: '/about/'
      #  title: 'About'
      #- url: '/contact/'
      #  title: 'Contact'
      #- url: '/elements/'
      #  title: 'Elements'


#-------------------------------
# Author Settings
author:
  author_name: Amit Mondal
  author_avatar: /images/01-1.jpg


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_avatar: /images/01-1.jpg
  hero_title: Hi! I’m Amit 👋
  hero_subtitle: A digital explorer and coder specializing in Java/OSGi/IoT, advocating for Green Software and AI.
  hero_description: |
    As a technophile, welcome to my digital sanctuary. It is my personal knowledge base, a place where I explore and unpack technical topics and the empowering world of information freedom. 
    
    I’m passionate about sharing curated resources that help me disseminate information effectively and maintain true mastery over my digital life. Explore, get inspired, and join the conversation!
  hero_image: /images/01.jpg
  #hero_image_caption: My creative space, where masterpieces are born
  hero_button_text: Let’s Connect
  hero_button_link: '/contact/'


# Logos
logos:
  enable: false
  logos_title: Nerd Stuff
  logo_image:
    - alt: "Game Boy"
      image: "/images/1000.jpg"
    - alt: "Super Nintendo"
      image: "/images/1001.jpg"
    - alt: "Keyboard"
      image: "/images/1002.jpg"
    - alt: "Headphones"
      image: "/images/1003.jpg"
    - alt: "Mouse"
      image: "/images/1004.jpg"


#-------------------------------
# Section Blog Settings
blog:
  enable: true
  blog_title: The Binary Journal


#-------------------------------
# Tags Section Settings
tags_section:
  enable: true
  tags_section_title: Hacker’s Haven
  tags:
    - tag: "SmartHome"
      image: "/images/tag-smarthome.jpg"
    - tag: "Programming"
      image: "/images/tag-programming.jpg"
    - tag: "LLM"
      image: "/images/tag-llm.jpg"
    - tag: "Sustainability"
      image: "/images/tag-sustainability.jpg"


#-------------------------------
# Videos Section Settings
videos_section:
  enable: false
  videos_section_title: Latest Videos


#-------------------------------
# Gallery Section Settings
gallery_section:
  enable: false
  gallery_section_title: Byte Frame
  gallery:
    gallery_images:
      - alt: 'Rest'
        url: '/images/100.jpg'
        caption: 'Small steps lead to big results.'
      - alt: 'Lifestyle'
        url: '/images/101.jpg'
        caption: 'A peaceful moment captured during a serene evening.'
      - alt: 'Hobby'
        url: '/images/102.jpg'
        caption: 'True friends are like stars — they shine brightest when the world feels dark.'
      - alt: 'Computers'
        url: '/images/103.jpg'
        caption: 'Every click opens a new chapter in an endless story.'
      - alt: 'Games'
        url: '/images/104.jpg'
        caption: 'Every level is a new opportunity to test your limits.'


#-------------------------------
# Newsletter Settings
mailchimp:
  enable: false
  mailchimp_title: Stay inspired weekly ✌️
  mailchimp_description: Every Sunday, I deliver actionable tips for enhancing productivity, practical life advice, and top-notch insights gathered from various sources, right to your email inbox.
  mailchimp_identifier: gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
  mailchimp_input_text: Your email address...
  mailchimp_button_text: Join Now


#-------------------------------
# Footer Settings
footer_description: Here, you’ll find a refined selection of content that I believe could be insightful for you. Explore what’s here, and don’t hesitate to share your thoughts!

#-------------------------------
# Social Settings
social:
- {icon: "fa-brands fa-linkedin-in", name: "LinkedIn", link: "https://linkedin.com/in/amitjoy"}
- {icon: "fa-brands fa-x-twitter", name: "X", link: "https://x.com/am1t_m0ndal"}
- {icon: "fa-brands fa-facebook", name: "Facebook", link: "https://www.facebook.com/amitjoy"}
#- {icon: "fa-brands fa-mastodon", name: "Mastodon", link: "https://mastodon.social"}
#- {icon: "fa-brands fa-reddit-alien", name: "Reddit", link: "https://reddit.com"}
- {icon: "fa-brands fa-github", name: "Github", link: "https://github.com/amitjoy"}
- {icon: "fa-brands fa-youtube", name: "Youtube", link: "https://www.youtube.com/lifebeyondcage"}
#- {icon: "fa-solid fa-rss", name: "Rss", link: "/feed.xml"}

# Example of adding a new link to the sidebar and footer - {icon: "fa-brands fa-youtube", name: "Youtube", link: https://youtube.com"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Contact Settings
contact:
  form_id: amit@amitinside.com # Add your form_id
  button_text: Send Now

# NOTE
# Coderon theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus:
  enable: true
  disqus_identifier: amitinside # Add your shortname for Disqus Comment. For example, anvod-studio-test
  disqus_title: Start the conversation
  disqus_button_text: Show Comments


#-------------------------------
# Google Analytics
google_analytics: # Add your GA Tracking Id